### ISSUE TITLE
Unicode with dmd

### ISSUE THREAD

**Issue by akshaythoke9116** [byronin/MQTT-DMD#1]
Hello Ronin,
How can we implement regional fonts using Unicode for the p10 display???

Can you help me??

**Comment by byronin** [comment]
Firstly I'm Ronin and I have not used unicode before. Beforehand we used the "http://www.apetech.de/fontCreator" but not usable and you can use "https://www.mikroe.com/glcd-font-creator". You can open the .h file of any font in the library and learn the necessary features and working structure.

**Comment by akshaythoke9116** [comment]
Ok thanks for the support

**Comment by akshaythoke9116** [comment]
And sorry for typo mistake
